swagger: "2.0"
info:
  title: NPM_TITLE
  description: "NPM_DESCRIPTION"
  version: "NPM_VERSION"
produces:
  - application/json
parameters:
  records:
    in: query
    name: records
    description: Number of records to appear
    type: integer
    minimum: 1
    maximum: MAX_LIMIT
    default: DEFAULT_LIMIT
  page:
    in: query
    name: page
    description: Page number based on records
    type: integer
    default: 0
  airport_identifier:
    in: path
    name: airport_identifier
    description: Either an id, iata_code or ident
    type: string
    required: true
  country_identifier:
    in: path
    name: country_identifier
    description: Either an id, code or code_3
    type: string
    required: true
  review_identifier:
    in: path
    name: review_identifier
    description: Review ID
    type: number
    required: true
paths:
  "/api/airports":
    post:
      summary: Add airport
      tags:
        - airports
      responses:
        "200":
          description: Returns new airport
        "400":
          description: Client sent through the wrong data
    get:
      summary: Get all airports
      tags:
        - airports
      parameters:
        - $ref: "#/parameters/records"
        - $ref: "#/parameters/page"
      responses:
        "200":
          description: Shows all airports within range
  "/api/airports/{airport_identifier}":
    parameters:
      - $ref: "#/parameters/airport_identifier"
      - in: query
        name: includes
        description: Add `reviews`
        type: array
        items:
          type: string
    put:
      summary: Update airport
      tags:
        - airports
      responses:
        "200":
          description: Returns new airport
    get:
      summary: Get airport by indentifer
      tags:
        - airports
      responses:
        "200":
          description: Shows airport details with any included additional fields
  "/api/airports/{airport_identifier}/reviews":
    parameters:
      - $ref: "#/parameters/airport_identifier"
    put:
      summary: Add airport's review
      tags:
        - airports
        - reviews
      responses:
        "200":
          description: Shows new airport review
    get:
      summary: Get all airport's reviews
      tags:
        - airports
        - reviews
      responses:
        "200":
          description: Show all reviews related to a particular airport
  "/api/countries":
    get:
      summary: Get all countries
      tags:
        - countries
      parameters:
        - $ref: "#/parameters/records"
        - $ref: "#/parameters/page"
      responses:
        "200":
          description: Shows all countries within range
  "/api/countries/{country_identifier}":
    parameters:
      - $ref: "#/parameters/country_identifier"
    get:
      summary: Get country by indentifer
      tags:
        - countries
      responses:
        "200":
          description: Shows country details
  "/api/review/{review_identifier}":
    parameters:
      - $ref: "#/parameters/review_identifier"
    get:
      summary: Get reivew by ID
      tags:
        - reviews
      responses:
        "200":
          description: Shows country details
    delete:
      summary: Delete reivew by ID
      tags:
        - reviews
      responses:
        "204":
          description: Deleted succesfully
